### ISSUE TITLE
Specify network for transactions

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#104]
**Is your feature request related to a problem? Please describe.**
At the moment there is a single global object that represents the current network. This makes it more error prone when in the same program we have to deal with all kind of networks. Also, I don't think it's thread safe (I'm not an expert on C# so I'm not sure).

**Describe the solution you'd like**
Change `Transaction.SignatureBase` (and other methods calling it) to accept a `Network` argument. If this argument is null, then use the global value like it does now.

**Comment by elucidsoft** [comment]
The reason its like this is to be consistent with the other Official Stellar SDKs such as the Java one.  The idea is if you needed to deal with multiple networks such as Test and Public you would have two Server objects.  As for it being ThreadSafe it is as long as you are using the async await model.

Instead of passing it in, I think a better way of doing it would be to modify the Server object so that it uses a Builder pattern so you would do something like:

`using(var server = Server.Use(Network.Public).Create())`

This way you wouldn't need to constantly pass in the parameter, and it would also set your Server object to a specific Network.  You could also do it as a ctor in the Server object but I would prefer to stick with the builder pattern as that is what's being used throughout the framework currently.

**Comment by fracek** [comment]
At the moment my use case does not involve Server, I'm just signing transactions (I receive some request for signing + which network to use). My worry is that between `Network.Use` and `Transaction.Sign` some other thread will call `Network.Use` with a different network, resulting in signing the wrong thing. Even using thread local storage would not solve the problem because in ASP.Net Core (I think) requests can share the same thread.

I was able to work around this limitation in my project so it is not a problem if you decide to not add this feature, I just wanted to share how I use your library and what's currently the (only) pain point I have with it :smile:

**Comment by elucidsoft** [comment]
I see, in that use case it would make sense to add an overload to the Sign method call.  We can easily do that to allow this kind of flexibility.

**Comment by fracek** [comment]
In that case I'm more than happy to do it. Thanks!

**Comment by bazooka70** [comment]
@fracek , After looking more closely at the code, the `Tansaction` overloads you made are dealing with the `Network.Current` and that issue is covered there.

I think the only other place the `Network.Current` is used is in the `FriendBotRequestBuilder` constructor (testnet only).

I really don't know why the `Network.Current` tests  are needed in the constructor:

```csharp
        public FriendBotRequestBuilder(Uri serverUri, HttpClient httpClient)
            : base(serverUri, "friendbot", httpClient)
        {
            if (Network.Current == null)
            {
                throw new NotSupportedException("FriendBot requires the TESTNET Network to be set explicitly.");
            }

            if (Network.IsPublicNetwork(Network.Current))
            {
                throw new NotSupportedException("FriendBot is only supported on the TESTNET Network.");
            }
        }
```

It is not used later for this class...

**Comment by bazooka70** [comment]
I made a pull request.
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/110

Possible usage:
```
var friendBot = await server.TestNetFriendBot
  .FundAccount(KeyPair.Random(), Network.Test())
  .Execute().Result;
```

**Comment by bazooka70** [comment]
Ok, never mind. some tests did not pass.  I deleted it.
