### ISSUE TITLE
AuthImmutable is missing in AssetResponseFlags

### ISSUE THREAD

**Issue by henryhwang** [elucidsoft/dotnet-stellar-sdk#145]
There is no AuthImmutable property defined in AssetResponseFlags class, which makes it kind of hard to retrieve that info for asset.

In fact, there is Flags class defined which includes everything. Is there any particular reason we don't use it for AssetResponse class, instead of defining another similar AssetResponseFlags?

**Comment by michaeljmonte** [comment]
Thanks for pointing this out.

I have actually been working in another branch to identify SDK support for the Horizon protocol. This was actually one of the first issues I had found. I am currently not complete with document, but this issue is known.

As for your second question, yes there is probably a reason, but probably not a good reason.

**Comment by michaeljmonte** [comment]
See #45
