### ISSUE TITLE
SEP-10: Make SIGNING_KEY required and change manage data op value

### ISSUE THREAD

**Issue by gaclaudiu** [elucidsoft/dotnet-stellar-sdk#275]
**Is your feature request related to a problem? Please describe.**
https://github.com/stellar/stellar-protocol/pull/708
**Describe the solution you'd like**
https://github.com/stellar/stellar-protocol/pull/708
**Describe alternatives you've considered**
https://github.com/stellar/stellar-protocol/pull/708
**Additional context**
https://github.com/stellar/stellar-protocol/pull/708

**Comment by elucidsoft** [comment]
We will get to this shortly.  Sorry for the delay.

**Comment by elucidsoft** [comment]
We implement SEP 2.0, we also verify the home domain per the original requirement.  In SEP 2.1 the requirement for home address validation is being loosened.  In addition, we don't validate any of the TOML contents, it's up to the developer to ensure the contents of the TOML are accurate.

If your not seeing support for SEP 2.0, you may need to update your SDK version.  I am closing this issue, since this issue didn't have a lot of additional information to go on I can only make the assumption this is why you opened it.  Please let me know if there is another reason.
