### ISSUE TITLE
Return dates as DateTime instead of string

### ISSUE THREAD

**Issue by tonik-ru** [elucidsoft/dotnet-stellar-sdk#326]
why do you use string properties for date values? for ex in TransactionResult.CreatedAt?

**Comment by elucidsoft** [comment]
It's like this in the Official Stellar SDK's for example:

Javascript SDK:
https://github.com/stellar/js-stellar-sdk/blob/563ab744785aeedfab1559a3e34a2141baa0268b/src/horizon_api.ts#L42

Java SDK: 
https://github.com/stellar/java-stellar-sdk/blob/07a70c3dcda68095eb92527e182d2aa75c1e45d2/src/main/java/org/stellar/sdk/responses/TransactionResponse.java#L24

In order to stay as close to the Official SDK behavior we kept the same structure types whenever possible.
