### ISSUE TITLE
Improve Code Coverage

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#43]
Write missing unit tests to improve code coverage to get it closer to 100% coverage.  This should be done with mocking as necessary.  EventSource may prove rather difficult to put under test for instance.

**Comment by Kirbyrawr** [comment]
I will try to help with this task from now on

**Comment by Kirbyrawr** [comment]
Hi i want to know if this task is difficult to do or not, i say this because you mentioned refactorize the EventSource part but i don't feel like i can do it right now with my knowledge, however i can help if it's things like the Memo tests i did or things like that.

Is there any way to check in the codecoverage project what files are missing test? 

Thank you!

**Comment by Kirbyrawr** [comment]
Hi thank you!

**Comment by Kirbyrawr** [comment]
Thank you, after checking i think i will be able to help with some of the scripts 🎉

**Comment by Kirbyrawr** [comment]
I will make a pull request for this just to see how the code coverage goes up, please don't merge it till we have more things.
